[package]
name = "notreux/space-fighter"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
ByteNet = "ffrostflame/bytenet@0.4.6"
React = "jsdotlua/react@17.1.0"
ReactReflex = "littensy/react-reflex@0.3.5"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
Reflex = "littensy/reflex@4.3.1"
Sift = "csqrl/sift@0.0.9"
UpsideEngine = "notreux/upsideengine@3.0.0"